config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'maps/show'
  end
  namespace :public do
    get 'tags/index'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do
    root to: 'sessions#new', as: :admin_root
    resources :users, only: [:index, :edit, :show, :update, :destroy]
    resources :tags, only: [:index, :edit, :update, :destroy]do
      get 'playgrounds', to: 'playgrounds#tagged', as: :playgrounds
     end
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create,:destroy]
      delete 'remove_image', on: :member
    end
    resources :playgrounds, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
      member do
        delete :remove_image
      end
    end
     get 'search', to: 'searches#search', as: 'search'
  end
  

   scope module: :public do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :post_comments, only: [:create,:destroy]
      delete 'remove_image', on: :member
    end
    resources :playgrounds, only: [:new, :index, :show, :create, :edit, :update]do
      member do
        delete :remove_image
      end
    end
    get '/mypage' => 'users#mypage', as: :mypage
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] 
    post "guest_sign_in", to: "sessions#guest_sign_in"
    resources :tags, only: [:show,:index] do
      get 'playgrounds', to: 'playgrounds#tagged', as: :playgrounds
    end
    get 'search', to: 'searches#search', as: 'search'
    resource :map, only: [:show]
  end

end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    @search_word = params[:word]
    @range = params[:range]
    @search_type = params[:search] 

    
    if @range == "ユーザー"
      @users = User.looks(params[:search], params[:word])
    elsif @range == "遊び場"
      @playgrounds = Playground.looks(params[:search], params[:word])
    elsif @range == "投稿"
      @posts = Post.looks(params[:search], params[:word])
    elsif @range == "タグ"
      @tags = Tag.looks(params[:search], params[:word])
    elsif @range == "コメント"
      @post_comments = PostComment.looks(params[:search], params[:word])
    else
    end
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/search.html.erb
<h2><%= @search_word %>の検索結果</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "ユーザー" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= image_tag user.get_avatar_image(50, 50), alt: user.nickname, class: "avatar-image" %>
          </td>
          <td>
          <%= link_to user.nickname, admin_user_path(user) %>
          </td>
        </tr>
      <% end %>
    </tbody>

  <% elsif @range == "遊び場" %>
    <tbody>
      <% @playgrounds.each do |playground| %>
        <tr>
          <td>
            <% if playground.playground_images.attached? %>
              <%= image_tag playground.playground_images.first.variant(resize_to_limit: [50, 50]), class: "thumbnail" %>
            <% end %>
          </td>
          <td><%= link_to playground.name, admin_playground_path(playground) %></td>
          <td><%= playground.description %></td>
          <td><%= playground.address %></td>
        </tr>
      <% end %>
    </tbody>

  <% elsif @range == "投稿" %>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <% if post.post_images.attached? %>
              <%= image_tag post.post_images.first.variant(resize_to_limit: [50, 50]), class: "thumbnail" %>
            <% end %>
          </td>
          <td><%= link_to post.title, admin_post_path(post) %></td>
          <td><%= post.body %></td>
        </tr>
      <% end %>
    </tbody>

  <% elsif @range == "タグ" %>
    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= link_to tag.name, admin_tag_playgrounds_path(tag) %></td>
        </tr>
      <% end %>
    </tbody>

  <% elsif @range == "コメント" %>
    <tbody>
      <% @post_comments.each do |comment| %>
        <tr>
          <td><%= link_to comment.comment, admin_post_path(comment.post) %></td>
          <td><%= link_to comment.nickname, admin_user_path(comment.user) %></td> 
          <td><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></td> 
        </tr>
      <% end %>
    </tbody>

  <% else %>
    <tbody>
      <h1>検索結果はありません</h1>
    </tbody>
  <% end %>
</table>