config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'maps/show'
  end
  namespace :public do
    get 'tags/index'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do
    root to: 'sessions#new', as: :admin_root
    resources :users, only: [:index, :edit, :show, :update, :destroy]
    resources :tags, only: [:index, :edit, :update, :destroy]do
      get 'playgrounds', to: 'playgrounds#tagged', as: :playgrounds
     end
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create,:destroy]
      delete 'remove_image', on: :member
    end
    resources :playgrounds, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
      member do
        delete :remove_image
      end
    end
     get 'search', to: 'searches#search', as: 'search'
  end
  

   scope module: :public do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :post_comments, only: [:create,:destroy]
      delete 'remove_image', on: :member
    end
    resources :playgrounds, only: [:new, :index, :show, :create, :edit, :update]do
      member do
        delete :remove_image
      end
    end
    get '/mypage' => 'users#mypage', as: :mypage
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] 
    post "guest_sign_in", to: "sessions#guest_sign_in"
    resources :tags, only: [:show,:index] do
      get 'playgrounds', to: 'playgrounds#tagged', as: :playgrounds
    end
    get 'search', to: 'searches#search', as: 'search'
    resource :map, only: [:show]
  end

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :playground
    belongs_to :user
    has_many :post_comments, dependent: :destroy
    has_many_attached :post_images
    has_many :post_taggings, dependent: :destroy
    has_many :tags, through: :post_taggings
    
    validates :title, presence: true, length: { maximum: 50 }
    validates :body, presence: true, length: { maximum: 300 }
    validate :validate_post_images

    # 仮想属性として tag_list を定義
    attr_accessor :tag_list

    # タグの保存処理を after_save で実行
    after_save :save_tags_from_list


    def get_post_image(width, height)
      unless post_image.attached?

        file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
        post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      post_image.variant(resize_to_limit: [width, height]).processed

    end

    def combined_images(new_images)
      # 既存の画像を取得し、新しい画像と結合
      existing_images = post_images.blobs
      # existing_images = post_images.attachments # 現在の画像データを取得
      combined = existing_images + Array(new_images) # 配列に変換し、新しい画像と結合
      # 合計枚数が8枚を超えている場合、nilを返す
      if combined.size > 8
        errors.add(:post_images, "は合計8枚までしか保存できません。")
        return nil
      end
      combined
    end


    def save_tags_from_list
      return unless tag_list.present?
    
      # タグをカンマやスペースで分割し、前後の空白を取り除いた配列を取得
      tag_names = tag_list.split(/[,\s;:#\u3000\uFF1A\uFF0C\uFF03]+/).map(&:strip).uniq

      # 現在のタグ名のリストを取得
      current_tags = self.tags.pluck(:name)
      old_tags = current_tags - tag_names
      new_tags = tag_names - current_tags
    
      # 古いタグの削除
      old_tags.each do |old_tag|
        tag = self.tags.find_by(name: old_tag)
        self.tags.delete(tag) if tag.present?
      end
    
      # 新しいタグの追加
      new_tags.each do |new_tag|
        tag = Tag.find_or_create_by(name: new_tag) # 既存のタグを検索し、存在しない場合のみ作成
        self.tags << tag unless self.tags.exists?(name: new_tag) # 重複を避けて関連に追加
      end
    end
  
    def update_tags(tag_names)
      # タグの重複を排除
      tag_names = tag_names.uniq
    
      # 現在のタグ名のリストを取得
      current_tags = self.tags.pluck(:name)
      old_tags = current_tags - tag_names
      new_tags = tag_names - current_tags
    
      # 古いタグの削除
      old_tags.each do |old_tag|
        tag = self.tags.find_by(name: old_tag)
        self.tags.delete(tag) if tag.present?
      end
    
      # 新しいタグの追加
      new_tags.each do |new_tag|
        tag = Tag.find_or_create_by(name: new_tag)
        self.tags << tag unless self.tags.exists?(name: new_tag)
      end
    end


    private

    def validate_post_images
      # 最大8枚の制限
      if post_images.count > 8
        errors.add(:post_images, "画像は最大8枚までアップロードできます")
      end
  
      # 各画像のサイズ制限（1MB = 1,048,576バイト）
      post_images.each do |image|
        if image.byte_size > 1.megabyte
          errors.add(:post_images, "各画像のサイズは1MB以下にしてください")
        end
      end
    end

    def self.looks(search, word)
      if search == "perfect_match"
        @posts = Post.where("title LIKE ? OR body LIKE ?", "#{word}", "#{word}").where(is_displayed: true).order(created_at: :desc)
      elsif search == "forward_match"
        @posts = Post.where("title LIKE ? OR body LIKE ?", "#{word}%", "#{word}%").where(is_displayed: true).order(created_at: :desc)
      elsif search == "backward_match"
        @posts = Post.where("title LIKE ? OR body LIKE ?", "%#{word}", "%#{word}").where(is_displayed: true).order(created_at: :desc)
      elsif search == "partial_match"
        @posts = Post.where("title LIKE ? OR body LIKE ?", "%#{word}%", "%#{word}%").where(is_displayed: true).order(created_at: :desc)
      else
        @posts = Post.where(is_displayed: true).order(created_at: :desc)
      end
    end

    
    

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    tags = parse_tags(params[:post][:tag_list])
    if post_params[:post_images].present?
      combined_images = @post.combined_images(params[:post][:post_images]) # 既存の画像と新しい画像を合わせて追加
    # combined_imagesがnilならば処理を停止し、エラーメッセージを表示
    if combined_images.present?
        params[:post][:post_images].each do |new_image|
          @post.post_images.attach(new_image)
        end
      else
        render :edit and return
      end
    end
    if @post.update(post_params.except(:post_images))
      @post.playground.post_update_tags(tags)
      flash[:notice] = "投稿が更新されました。"
      redirect_to admin_post_path(@post)
    else
      flash[:alert] = "投稿の更新に失敗しました。"
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.post_comments.destroy_all
    if @post.destroy
      flash[:notice] = "投稿が削除されました。"
      redirect_to admin_playground_path(@post.playground) 
    else
      flash[:alert] = "投稿の削除に失敗しました。"
      redirect_to admin_playground_path(@post.playground) 
    end
  end

  def remove_image
    @post = Post.find(params[:id])
    image = @post.post_images.find(params[:image_id])
    image.purge # ActiveStorage の画像を削除するメソッド
  
    redirect_to edit_admin_post_path(@post), notice: '画像が削除されました。'
  end

  private

  def post_params
    params.require(:post).permit(:playground_id, 
                                 :title, 
                                 :body,
                                 :tag_list,
                                 :star, 
                                 :is_displayed, 
                                 post_images: [])
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<div class="form-group row" style="padding:20px;">
  <div class="col-6 offset-3" style="border-radius: 30px; background-color: #5ce0e5; padding-top:5px;">
    <h2 class="text-center" style="color: #dc3d26;"><%= @post.title %>の編集</h2>
  </div>
</div>
<%= render 'public/shared/flash' %>

<div class="row justify-content-center min-vh-100">
  <%= form_with model: @post, url: admin_post_path(@post), method: :patch, local: true do |f| %>
    <%= render "public/shared/error_messages", resource: @post %>

    <div class="row">
      <!-- 左側のカラム -->
      <div class="col-md-6">
        <div class="form-group row border-bottom">
          <div class="col-5 d-flex align-items-center">
            <span>タイトル</span>
            <span class="ml-2" style="font-size: 0.8rem; gray;">50文字まで</span>
          </div>
          <div class="col-7" style="margin-bottom: 10px;">
            <%= f.text_field :title, required: true, class: "w-100" %>
          </div>
        </div>

        <div class="form-group row border-bottom">
          <div class="col-5 d-flex align-items-center">
            <span>本文</span>
            <span class="ml-2" style="font-size: 0.8rem; gray;">500文字まで</span>
          </div>
          <div class="col-7" style="margin-bottom: 10px;">
            <%= f.text_area :body, required: true, class: "w-100" %>
          </div>
        </div>

        <div class="form-group row border-bottom">
          <div class="col-5">
            <span>評価</span>
          </div>
          <div class="col-7" style="margin-bottom: 10px;">
            <%= f.number_field :star, step: 0.5, min: 0, max: 5, class: "w-100" %>
          </div>
        </div>

        <div class="form-group row border-bottom">
          <div class="col-2 d-flex align-items-center">
            <span>タグ</span>
          </div>
          <div class="col-3 d-flex align-items-center">
            <span class="ml-2" style="font-size: 0.8rem; gray;">全角のカンマかスペース、＃で区切ってください</span>
          </div>
          <div class="col-7" style="margin-bottom: 10px;">
            <%= f.text_field :tag_list, value: @post.tags.map(&:name).join(", "), placeholder: "タグをカンマかスペースで区切って入力", class: "w-100" %>
          </div>
        </div>
        <div class="form-group row border-bottom justify-content-center">
          <div class="col-5">ステータス</div>
          <div class="col-7" style="margin-bottom: 15px;">
            <%= f.radio_button :is_displayed, :true %>
            <%= f.label :is_deleted, "表示"  %>
            <%= f.radio_button :is_displayed, :false %>
            <%= f.label :is_deleted, "非表示" %>
          </div>
        </div> 
      </div>

      <!-- 右側のカラム -->
      <div class="col-md-6">
        <div class="field">
          <%= f.label :post_images, "画像の追加・編集" %>
           <%= f.file_field :post_images, multiple: true, direct_upload: true, id: "post_images", accept: "image/jpeg,image/png,image/gif" %></br>
          <p>※ 既存の画像は以下に表示されます。削除する場合は画像を選択して削除を実行してください。</p>
          <div class="post-images">
            <% @post.post_images.each do |image| %>
              <div class="image-preview">
                <%= image_tag image.variant(resize_to_limit: [100, 100]), class: "post-image popup" %>
               <%= link_to '削除', remove_image_admin_post_path(@post, image_id: image.id), method: :delete, data: { confirm: 'この画像を削除しますか？' } %>
              </div>
            <% end %>
          </div>
        </div>
      </div>


    </div>

    <!-- 送信ボタンを下中央に配置 -->
    <div class="row justify-content-center mt-4">
      <div class="col-auto">
        <%= f.submit "更新する", class: "btn btn-primary" %>
        <%= link_to 'キャンセル', admin_post_path(@post), class: 'btn btn-secondary' %>
      </div>
    </div>
  <% end %>
</div>
<%= javascript_pack_tag "post_images",  'data-turbolinks-track': 'reload' %>

app/views/admin/posts/index.html.erb
<div class="row" style="display: flex; align-items: center; justify-content: space-between;">
  <h2 style="margin-left: 10px;">投稿一覧</h2>
</div>

      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>投稿ID</th>
            <th></th>
            <th>タイトル</th>
            <th>評価</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.id %></td>
              <td>
                <% if post.post_images.attached? %>
                  <%= image_tag post.post_images.first.variant(resize_to_limit: [100, 100]), class: "thumbnail popup" %>
                <% else %>
                  <span>画像はありません</span>
                <% end %>
              </td>
              <td><%= link_to post.title, admin_post_path(post) %></td>
              <td>
                <%= render "/public/posts/static_rate", post: post %>
              </td>
              <td>
              <% if post.is_displayed == true %>
                <div class="text-success font-weight-bolder">表示</div>
              <% else %>
                <div class="text-muted font-weight-bolder">非表示</div>
              <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <%= paginate @posts, class: "text-center" %>
   
 

app/views/admin/posts/show.html.erb
<%= render 'public/shared/flash' %>
<div class="row min-vh-100">
  <div class="col-7 mt-3">
    <div class="post-images mt-3">
      <% if @post.post_images.attached? %>
        <% @post.post_images.each do |image| %>
          <%= image_tag image, class: "post-image", size: "200x150" %>
        <% end %>
      <% else %>
        <p>画像がありません</p>
      <% end %>
    </div>
    <div>
      <p><strong>タイトル:</strong> <%= @post.title %></p>
      <p><strong>本文:</strong> <%= @post.body %></p>
      <p>
        <strong>タグ:</strong> 
        <% @post.tags.each_with_index do |tag, index| %>
          <%= link_to tag.name, admin_tag_playgrounds_path(tag) %><%= ", " unless index == @post.tags.size - 1 %>
        <% end %>
      </p>
      <p><strong>遊び場:</strong> <%= link_to @post.playground.name, admin_playground_path(@post.playground) %></p>
      <p>
      <p><strong>投稿者:</strong> <%= link_to @post.user.nickname, admin_user_path(@post.user) %></p>
      <p><strong>評価:</strong><%= render "public/posts/static_rate", post: @post %></p>
      <%= link_to '編集する', edit_admin_post_path(@post), class: 'btn btn-primary' %>
      <%= link_to '削除する', admin_post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
      <%= link_to '遊び場に戻る', admin_playground_path(@post.playground), class: 'btn btn-secondary' %>
    </div>
  </div>

  <div class="col-5 mt-3">

    <div class="flex">
      <h4>コメント<div style="font-size: 14px;"><%= @post.post_comments.count %>件</div></h4>
    </div>
    <% @post.post_comments.each do |post_comment| %>
      <div class="row comment">
        <div class="col-11">
          <p><strong><%= link_to post_comment.user.nickname, user_path(post_comment.user) %></strong>: <%= post_comment.comment %></p>
        </div>
        <div class="col-1 ml-auto text-right">
          <%= link_to '削除', admin_post_post_comment_path(@post, post_comment), method: :delete, data: { confirm: 'コメントを削除してもよろしいですか？' }, class: 'btn btn-danger btn-sm' %>
        </div>
      </div>
    <% end %>
  </div>
</div>