config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'maps/show'
  end
  namespace :public do
    get 'tags/index'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do
    root to: 'sessions#new', as: :admin_root
    resources :users, only: [:index, :edit, :show, :update, :destroy]
    resources :tags, only: [:index, :edit, :update, :destroy]do
      get 'playgrounds', to: 'playgrounds#tagged', as: :playgrounds
     end
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create,:destroy]
      delete 'remove_image', on: :member
    end
    resources :playgrounds, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
      member do
        delete :remove_image
      end
    end
     get 'search', to: 'searches#search', as: 'search'
  end
  

   scope module: :public do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :post_comments, only: [:create,:destroy]
      delete 'remove_image', on: :member
    end
    resources :playgrounds, only: [:new, :index, :show, :create, :edit, :update]do
      member do
        delete :remove_image
      end
    end
    get '/mypage' => 'users#mypage', as: :mypage
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] 
    post "guest_sign_in", to: "sessions#guest_sign_in"
    resources :tags, only: [:show,:index] do
      get 'playgrounds', to: 'playgrounds#tagged', as: :playgrounds
    end
    get 'search', to: 'searches#search', as: 'search'
    resource :map, only: [:show]
  end

end

app/models/playground.rb
class Playground < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings


  belongs_to :user, optional: true
  has_many_attached :playground_images

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :post_code, presence: true, format: { with: /\A\d{7}\z/, message: "はハイフンなしの7文字の数字で入力してください" }
  validates :phone_number, presence: true, uniqueness: true,format: { with: /\A\d{10,11}\z/, message: "はハイフンなしの10～11文字の数字で入力してください"  }
  validate :validate_playground_images

  geocoded_by :address
  after_validation :geocode

  # 仮想属性として tag_list を定義
  attr_accessor :tag_list

  # タグの保存処理を after_save で実行
  after_save :save_tags_from_list

  # 画像のリサイズメソッド
  def get_playground_image(width, height)
    unless playground_images.attached?

      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      playground_images.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    playground_images.first.variant(resize_to_limit: [width, height]).processed
  end
  

  def combined_images(new_images)
    # 既存の画像を取得し、新しい画像と結合
    existing_images = playground_images.blobs# 現在の画像データを取得
    combined = existing_images + Array(new_images) # 配列に変換し、新しい画像と結合
    # 合計枚数が8枚を超えている場合、nilを返す
    if combined.size > 8
      errors.add(:playground_images, "は合計8枚までしか保存できません。")
      return nil
    end
    combined
  end


  def self.looks(search, word)
    if search == "perfect_match"
      @playgrounds = Playground.where("name LIKE ? OR description LIKE ? OR address LIKE ?", "#{word}", "#{word}", "#{word}").order(created_at: :desc)
    elsif search == "forward_match"
      @playgrounds = Playground.where("name LIKE ? OR description LIKE ? OR address LIKE ?", "#{word}%", "#{word}%", "#{word}%").order(created_at: :desc)
    elsif search == "backward_match"
      @playgrounds = Playground.where("name LIKE ? OR description LIKE ? OR address LIKE ?", "%#{word}", "%#{word}", "%#{word}").order(created_at: :desc)
    elsif search == "partial_match"
      @playgrounds = Playground.where("name LIKE ? OR description LIKE ? OR address LIKE ?", "%#{word}%", "%#{word}%", "%#{word}%").order(created_at: :desc)
    else
      @playgrounds = Playground.order(created_at: :desc)
    end
  end

  def save_tags_from_list
    return unless tag_list.present?
  
    # タグをカンマやスペースで分割し、前後の空白を取り除いた配列を取得
    tag_names = tag_list.split(/[,\s;:#\u3000\uFF1A\uFF0C\uFF03]+/).map(&:strip).uniq
  
    # 現在のタグ名のリストを取得
    current_tags = self.tags.pluck(:name)
    old_tags = current_tags - tag_names
    new_tags = tag_names - current_tags
  
    # 古いタグの削除
    old_tags.each do |old_tag|
      tag = self.tags.find_by(name: old_tag)
      self.tags.delete(tag) if tag.present?
    end
  
    # 新しいタグの追加
    new_tags.each do |new_tag|
      tag = Tag.find_or_create_by(name: new_tag) # 既存のタグを検索し、存在しない場合のみ作成
      self.tags << tag unless self.tags.exists?(name: new_tag) # 重複を避けて関連に追加
    end


  end

  def update_tags(tag_names)
    return unless tag_names.present?
    # タグの重複を排除
    tag_names = tag_names.split(",") if tag_names.is_a?(String)
    tag_names = tag_names.map(&:strip).uniq
  
    # 現在のタグ名のリストを取得
    current_tags = self.tags.pluck(:name)
    old_tags = current_tags - tag_names
    new_tags = tag_names - current_tags
  
    # 古いタグの削除
    old_tags.each do |old_tag|
      tag = self.tags.find_by(name: old_tag)
      self.tags.delete(tag) if tag.present?
    end
  
    # 新しいタグの追加
    new_tags.each do |new_tag|
      tag = Tag.find_or_create_by(name: new_tag)
      self.tags << tag unless self.tags.exists?(name: new_tag)
    end
  end
  
  # postから追加のタグを登録する
  def post_update_tags(tag_names)
    return unless tag_names.present?
    # タグの重複を排除
    tag_names = tag_names.split(",") if tag_names.is_a?(String)
    tag_names = tag_names.map(&:strip).uniq
  
    # 現在のタグと元々のタグを合わせる
    current_tags = self.tags.pluck(:name)
    new_tags = tag_names + current_tags
  
    # 合わせたタグの追加
    new_tags.each do |new_tag|
      tag = Tag.find_or_create_by(name: new_tag)
      self.tags << tag unless self.tags.exists?(name: new_tag)
    end
  end

  private

  def validate_playground_images
    # 最大8枚までの制限
    if playground_images.count > 8
      errors.add(:playground_images, "画像は合計で8枚までアップロード可能です")
    end
  
    playground_images.each do |image|
      # 各画像のサイズ制限 (1MB = 1,048,576 bytes)
      if image.byte_size > 1.megabyte
        errors.add(:playground_images, "各画像のサイズは1MB以下にしてください")
      end
  
      # ファイル形式の制限 (画像ファイルのみ許可)
      unless image.content_type.start_with?('image/')
        errors.add(:playground_images, "画像ファイルのみアップロード可能です")
      end
    end
  end


end

app/controllers/admin/playgrounds_controller.rb
class Admin::PlaygroundsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @playgrounds = Playground.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @playground = Playground.new
  end

  def tagged
    # パラメータからタグを見つけ、そのタグに紐づいたPlaygroundを取得
    @tag = Tag.find(params[:tag_id])
    @playgrounds = @tag.playgrounds
  end

  def create
    @playground = Playground.new(playground_params)
    tags = parse_tags(params[:playground][:tag_id])

    if @playground.save
      @playground.update_tags(params[:playground][:tag_list])
      flash[:notice] = "新しい遊び場が作成されました。"
      redirect_to admin_playground_path(@playground)
    else
      flash[:alert] = "遊び場の作成に失敗しました。"
      render :new
    end
  end

  def show
    @playground = Playground.find(params[:id])
    @playgrounds = Playground.page(params[:page]).per(10)
  end

  def edit
    @playground = Playground.find(params[:id])
  end

  def update
    @playground = Playground.find(params[:id])
    tags = parse_tags(params[:playground][:tag_id])
    if playground_params[:playground_images].present?
      combined_images = @playground.combined_images(params[:playground][:playground_images]) # 既存の画像と新しい画像を合わせて追加
      if combined_images.present?
        params[:playground][:playground_images].each do |new_image|
          @playground.playground_images.attach(new_image)
        end
      else
        render :edit and return
      end
    end
    
    if @playground.update(playground_params.except(:playground_images)) # 画像以外の属性を更新
      @playground.update_tags(tags)
      flash[:notice] = '遊び場が更新されました。'
      redirect_to admin_playground_path(@playground)
    else
      flash[:alert] = '遊び場の更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @playground = Playground.find(params[:id])
    if @playground.destroy
      flash[:notice] = "遊び場が削除されました。"
      redirect_to admin_playgrounds_path
    else
      flash[:alert] = "遊び場の削除に失敗しました。"
      redirect_to admin_playground_path(@playground)
    end
  end


  private


  def playground_params
    params.require(:playground).permit(:name, 
                                       :description,
                                       :tag_list,
                                       :post_code, 
                                       :address, 
                                       :phone_number, 
                                       :is_active, 
                                       :user_id,
                                       playground_images: [])
  end

end

app/helpers/admin/playgrounds_helper.rb
module Admin::PlaygroundsHelper
end

app/views/admin/playgrounds/edit.html.erb
<div class="form-group row" style="padding:20px;">
  <div class="col-6 offset-3" style="border-radius: 30px; background-color: #5ce0e5; padding-top:5px;">
    <h2 class="text-center" style="color: #dc3d26;"><%= @playground.name %>の編集</h2>
  </div>
</div>
<%= render 'public/shared/flash' %>

<div class="row justify-content-center min-vh-100">
  <%= form_with model: @playground, url: admin_playground_path(@playground), method: :patch, local: true do |f| %>
    <%= render "public/shared/error_messages", resource: @playground %>

    <div class="row">
      <!-- 左側のカラム -->
      <div class="col-md-6">
        <div class="form-group row border-bottom">
          <div class="col-5 d-flex align-items-center">
            <span>遊び場名</span>
            <span class="ml-2" style="font-size: 0.8rem; gray;">20文字まで</span>
          </div>
          <div class="col-7" style="margin-bottom: 10px;">
            <%= f.text_field :name, required: true, class: "w-100", maxlength: 50 %>
          </div>
        </div>

        <div class="form-group row border-bottom">
          <div class="col-5 d-flex align-items-center">
            <span>説明</span>
            <span class="ml-2" style="font-size: 0.8rem; gray;">300文字まで</span>
          </div>
          <div class="col-7" style="margin-bottom: 10px;">
            <%= f.text_area :description, required: true, class: "w-100", maxlength: 500 %>
          </div>
        </div>

        <div class="form-group row border-bottom">
            <div class="col-2 d-flex align-items-center">
              <span>タグ</span>
            </div>
            <div class="col-3 d-flex align-items-center">
              <span class="ml-2" style="font-size: 0.8rem; gray;">全角のカンマかスペース、＃で区切ってください</span>
            </div>
            <div class="col-7" style="margin-bottom: 10px;">
            <%= f.text_field :tag_list, value: @playground.tags.map(&:name).join(", "), placeholder: "タグをカンマかスペースで区切って入力", class: "w-100" %>
          </div>
        </div>

        <div class="form-group row border-bottom">
          <div class="col-5">
            郵便番号
          </div>
          <div class="col-7" style="margin-bottom: 10px;">
            <%= f.text_field :post_code, required: true, class: "w-100", maxlength: 7, pattern: "\\d{7}", title: "7文字の数字を入力してください" %>
          </div>
        </div>

        <div class="form-group row border-bottom">
          <div class="col-5">
            住所
          </div>
          <div class="col-7" style="margin-bottom: 10px;">
            <%= f.text_area :address, required: true, class: "w-100" %>
          </div>
        </div>

        <div class="form-group row border-bottom">
          <div class="col-5">
            電話番号
          </div>
          <div class="col-7" style="margin-bottom: 10px;">
            <%= f.text_field :phone_number, required: true, class: "w-100", pattern: "\\d{10,11}", maxlength: 11, title: "ハイフンなしの10～11文字の数字を入力してください" %>
          </div>
        </div>

        <div class="form-group row border-bottom justify-content-center">
          <div class="mr-5">
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "営業" %>
          </div>
          <div>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "閉業" %>
          </div>
        </div>
      </div>

      <!-- 右側のカラム -->
      <div class="col-md-6">
      <div class="field">
        <%= f.label :playground_images, "画像の追加・編集" %>
        <%= f.file_field :playground_images, multiple: true, direct_upload: true, id: "playground_images", accept: "image/jpeg,image/png,image/gif" %>
        <p>1枚1MB以下合計8枚まで</p>
        <p>※ 既存の画像は以下に表示されます。削除する場合は画像を選択して削除を実行してください。</p>
        <div class="playground-images">
          <% @playground.playground_images.each do |image| %>
            <div class="image-preview">
              <%= image_tag image.variant(resize_to_limit: [100, 100]), class: "playground-image popup" %>
              <%= link_to '削除', remove_image_playground_path(@playground, image_id: image.id), method: :delete, data: { confirm: 'この画像を削除しますか？' } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <!-- 送信ボタンを下中央に配置 -->
    <div class="row justify-content-center mt-4">
      <div class="col-auto">
        <%= f.submit "更新する", class: "btn btn-primary" %>
        <%= link_to 'キャンセル', admin_playground_path(@playground), class: 'btn btn-secondary' %>
      </div>
    </div>
  <% end %>
</div>
<%= javascript_pack_tag "jpostal",  'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag "playground_images",  'data-turbolinks-track': 'reload' %>

app/views/admin/playgrounds/index.html.erb
<div class="row" style="display: flex; align-items: center; justify-content: space-between;">
    <h2 style="margin-left: 10px;">遊び場一覧</h2>
  <div class="mb-3">
    <%= link_to "新しい遊び場の登録" ,new_admin_playground_path, class:"btn btn-lg btn-primary" %>
  </div> 
</div>

 

      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>遊び場ID</th>
            <th>施設名</th>
            <th>住所</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @playgrounds.each do |playground| %>
            <tr>
              <td><%= playground.id %></td>
              <td><%= link_to playground.name, admin_playground_path(playground) %></td>
              <td><%= playground.address %></td>
              <td>
              <% if playground.is_active == true %>
                <div class="text-success font-weight-bolder">営業</div>
              <% else %>
                <div class="text-muted font-weight-bolder">閉業</div>
              <% end %>
              </td>
            </tr>
            <% end %>
            
        </tbody>
      </table>
       <%= paginate @playgrounds,class: "text-center" %>

app/views/admin/playgrounds/new.html.erb
<div class="form-group row" style="padding:20px;">
  <div class="col-6 offset-3" style="border-radius: 30px; background-color: #5ce0e5; padding-top:5px;">
    <h2 class="text-center" style="color: #dc3d26;">新しい遊び場登録</h2>
  </div>
</div>
<%= render 'public/shared/flash' %>

<div class="px-5">
  <%= form_with model: @playground, url: admin_playgrounds_path,local: true do |f| %>
    <%= render "public/shared/error_messages", resource: @playground %>

    <div class="form-group row border-bottom">
      <div class="col-5 d-flex align-items-center">
        <span>遊び場名</span>
        <span class="ml-2" style="font-size: 0.8rem; gray;">50文字まで</span>
      </div>
      <div class="col-7" style="margin-bottom: 10px;">
        <%= f.text_field :name, required: true, class: "w-100", maxlength: 50 %>
      </div>
    </div>


    <div class="form-group row border-bottom">
      <div class="col-5 d-flex align-items-center">
        <span>説明</span>
        <span class="ml-2" style="font-size: 0.8rem; gray;">500文字まで</span>
      </div>
      <div class="col-7" style="margin-bottom: 10px;">
        <%= f.text_area :description, required: true, class: "w-100", maxlength: 500 %>
      </div>
    </div>
    
    <div class="form-group row border-bottom">
      <div class="col-5 d-flex align-items-center">
        <span>タグ</span>
        <span class="ml-2" style="font-size: 0.8rem; gray;">全角のカンマかスペース、＃で区切ってください</span>
      </div>
      <div class="col-7" style="margin-bottom: 10px;">
        <%= f.text_field :tag_list, value: @playground.tags.map(&:name).join(", "), placeholder: "全角のカンマかスペース、＃で区切ってください", class: "w-100" %>
      </div>
    </div>

    <div class="form-group row border-bottom">
      <div class="col-5 d-flex align-items-center">
        <span>画像</span>
        <span class="ml-2" style="font-size: 0.8rem; gray;">1枚1MB以下合計8枚まで</span>
      </div>
      <div class="col-7" style="margin-bottom: 10px;">
                <%= f.file_field :playground_images, multiple: true, direct_upload: true, id: "playground_images", accept: "image/jpeg,image/png,image/gif" %>
      </div>
    </div>

    <div class="form-group row border-bottom">
      <div class="col-5">
        郵便番号
      </div>
      <div class="col-7" style="margin-bottom: 10px;">
        <%= f.text_field :post_code, required: true, class: "w-100", maxlength: 7, pattern: "\\d{7}", title: "7文字の数字を入力してください" %>
      </div>
    </div>

    <div class="form-group row border-bottom">
      <div class="col-5">
        住所
      </div>
      <div class="col-7" style="margin-bottom: 10px;">
        <%= f.text_area :address, required: true, class: "w-100" %>
      </div>
    </div>
    
    <div class="form-group row border-bottom">
      <div class="col-5 d-flex align-items-center">
        <span>電話番号</span>
        <span class="ml-2" style="font-size: 0.8rem; gray;">ハイフンなしの10～11桁の数字</span>
      </div>
      <div class="col-7" style="margin-bottom: 10px;">
        <%= f.text_field :phone_number, required: true, class: "w-100", pattern: "\\d{10,11}", maxlength: 11, title: "ハイフンなしの10～11文字の数字を入力してください" %>
      </div>
    </div>
    
    <%= f.hidden_field :is_active, value: "true" %>

    <div class="row" style="padding-bottom:20px;">
      <div class="col-12 text-center">
        <%= f.submit "遊び場登録", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>
<%= javascript_pack_tag "jpostal",  'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag "playground_images",  'data-turbolinks-track': 'reload' %>

app/views/admin/playgrounds/show.html.erb
<%= render 'public/shared/flash' %>
<div class="form-group row" style="padding:20px;">
  <div class="col-6 offset-3" style="border-radius: 30px; background-color: #5ce0e5; padding-top:5px;">
    <h2 class="text-center" style="color: #dc3d26;"><%= @playground.name %>の情報</h2>
  </div>
</div>
  <div class="row">
    <div class="col-4 ">
      <p><strong>説明:</strong> <%= @playground.description %></p>
      <p>
        <strong>タグ:</strong> 
        <% @playground.tags.each_with_index do |tag, index| %>
          <%= link_to tag.name, admin_tag_playgrounds_path(tag) %><%= ", " unless index == @playground.tags.size - 1 %>
        <% end %>
      </p>
      <p><strong>郵便番号:</strong> <%= @playground.post_code %></p>
      <p><strong>住所:</strong> <%= @playground.address %></p>
      <p><strong>電話番号:</strong> <%= @playground.phone_number %></p>
      <p><strong>ステータス:</strong> <%= @playground.is_active ? "営業" : "閉業" %></p>
      <div style="display: flex;"><strong>評価:</strong> <%= @playground.posts.count %>件<%= render "/public/playgrounds/average_rate.html.erb", playground: @playground %></div>
      <div class="my-3">
        <%= link_to '編集', edit_admin_playground_path(@playground), class: 'btn btn-primary' %>
        <%= link_to 'この遊び場の削除', admin_playground_path(@playground), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger'  %>
      </div>
    </div>
    <div class="col-8 playground-images">
      <% if @playground.playground_images.attached? %>
         <% @playground.playground_images.each do |image| %>
          <%= image_tag image, class: "playground-image", size: "200x150" %>
        <% end %>
      <% else %>
        <p>画像がありません</p>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <!--  playgroundの投稿一覧 -->
      <h3>投稿一覧</h3>
      <table class="table table-striped">
        <tbody>
            <% @playground.posts.each do |playground_post| %> 
            <tr>
              <td>
                <% if playground_post.post_images.attached? %>
                  <%= image_tag playground_post.post_images.first.variant(resize_to_limit: [100, 100]), class: "thumbnail popup" %>
                <% else %>
                  <span>画像はありません</span>
                <% end %>
              </td>
              <td>
                <%= link_to playground_post.title, admin_post_path(playground_post) %>
              </td>
              <td>
                <%= render "/public/posts/static_rate", post: playground_post %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <%= paginate @playgrounds %>
    
  </div>

app/views/admin/playgrounds/tagged.html.erb
<h1><%= @tag.name %>に関連する遊び場</h1> <!-- タグ名を表示 -->

<table>
  <thead>
    <tr>
      <th></th>
      <th>遊び場名</th>
      <th>住所</th>
      <th>説明</th>
    </tr>
  </thead>
  <tbody>
    <% @playgrounds.each do |playground| %>
      <tr>
        <td>
          <% if playground.playground_images.attached? %>
            <%= image_tag playground.playground_images.first.variant(resize_to_limit: [50, 50]), class: "thumbnai popupl" %>
          <% end %>
        </td>
        <td><%= link_to playground.name, admin_playground_path(playground) %></td> <!-- Playgroundの詳細ページリンク -->
        <td><%= playground.address %></td>
        <td><%= playground.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>