config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'maps/show'
  end
  namespace :public do
    get 'tags/index'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end


  namespace :admin do
    root to: 'sessions#new', as: :admin_root
    resources :users, only: [:index, :edit, :show, :update, :destroy]
    resources :tags, only: [:index, :edit, :update, :destroy]do
      get 'playgrounds', to: 'playgrounds#tagged', as: :playgrounds
     end
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create,:destroy]
      delete 'remove_image', on: :member
    end
    resources :playgrounds, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
      member do
        delete :remove_image
      end
    end
     get 'search', to: 'searches#search', as: 'search'
  end
  

   scope module: :public do
    root to: "homes#top"
    get "about", to: "homes#about"
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :post_comments, only: [:create,:destroy]
      delete 'remove_image', on: :member
    end
    resources :playgrounds, only: [:new, :index, :show, :create, :edit, :update]do
      member do
        delete :remove_image
      end
    end
    get '/mypage' => 'users#mypage', as: :mypage
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] 
    post "guest_sign_in", to: "sessions#guest_sign_in"
    resources :tags, only: [:show,:index] do
      get 'playgrounds', to: 'playgrounds#tagged', as: :playgrounds
    end
    get 'search', to: 'searches#search', as: 'search'
    resource :map, only: [:show]
  end

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <h4><%= obj.errors.count %>件のエラーが発生したため、保存ができませんでした。</h4>
　　<ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class='text-center'style="background-color: #5ce0e5; height: 100px;">Asobi-Note</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="row">
    <nav class="navbar navbar-expand-lg w-100" style="background-color: #5ce0e5;">
      <div class="col-md-4 d-flex align-items-center">
        <h1><%= link_to image_tag("asobinote_logo.png", alt: "Title Logo", size: "300x100"), "/" %></h1>
      </div>

      <div id="sp-menu">
        <div class="class="mx-auto""><h2>MENU</h2></div>
        <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <!--ユーザーがログインしている時 -->
              <li class="m-3"><%= link_to "About", about_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "マイページ", mypage_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "遊び場一覧", playgrounds_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "投稿一覧", posts_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "タグ一覧", tags_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-custom" %></li>

            <% elsif admin_signed_in? %>
              <!-- 管理者がログインしている時 -->
              <li class="mb-3"><%= link_to "ユーザー一覧", admin_users_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "遊び場一覧", admin_playgrounds_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "投稿一覧" , admin_posts_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "タグ一覧", admin_tags_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-custom" %></li>

            <% else %>
              <!-- ログインしていない時 -->
              <li class="mb-3"><%= link_to "About", about_path, class: "btn btn-custom " %></li>
              <li class="mb-3"><%= link_to "新規登録", new_user_registration_path, class: "btn btn-custom" %></li>
              <li class="mb-3"><%= link_to "ログイン", new_user_session_path, class: "btn btn-custom" %></li>
            <% end %>
          </ul>
      </div>

      <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>


      <div class="col-md-2 text-center d-flex align-items-center">
        <% if user_signed_in? %>
          ようこそ、<%= current_user.nickname %>さん！
        <% end %>
      </div>
      <div class="col-md-6"> 
        <div class="collapse navbar-collapse" id="nav-pc">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <!--ユーザーがログインしている時 -->
              <li><%= link_to "About", about_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "マイページ", mypage_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "遊び場一覧", playgrounds_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "投稿一覧", posts_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "タグ一覧", tags_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-custom" %></li>

            <% elsif admin_signed_in? %>
              <!-- 管理者がログインしている時 -->
              <li><%= link_to "ユーザー一覧", admin_users_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "遊び場一覧", admin_playgrounds_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "投稿一覧" , admin_posts_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "タグ一覧", admin_tags_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-custom" %></li>

            <% else %>
              <!-- ログインしていない時 -->
              <li><%= link_to "About", about_path, class: "btn btn-custom " %></li>
              <li class="ml-3"><%= link_to "新規登録", new_user_registration_path, class: "btn btn-custom" %></li>
              <li class="ml-3"><%= link_to "ログイン", new_user_session_path, class: "btn btn-custom" %></li>
            <% end %>
          </ul>
        </div>
        <div class="d-flex justify-content-end mt-3">
          <%= render "layouts/search" %>
        </div>
      </div>
    </nav>
  </div>
   
</header>

app/views/layouts/_search.html.erb
  <div class="row">
    <% if user_signed_in? %>
      <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word, placeholder: "検索", class: "search-input" %>
            <%= f.select :range, options_for_select([['ユーザー'], ['遊び場'],['投稿'], ['タグ'], ['コメント']]) %>
            <%= f.hidden_field :search, value: "partial_match" %>
          <button type="submit" class="btn btn-outline-dark">
            <i class="fas fa-search"></i>
          </button>
        <% end %>
      </div>
    <% elsif admin_signed_in? %>
      <div class="search_form">
        <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word, placeholder: "検索", class: "search-input" %>
            <%= f.select :range, options_for_select([['ユーザー'], ['遊び場'],['投稿'], ['タグ'], ['コメント']]) %>
            <%= f.hidden_field :search, value: "partial_match" %>
          <button type="submit" class="btn btn-outline-dark">
            <i class="fas fa-search"></i>
          </button>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asobinote</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/4c2477e0ba.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

  </head>

  <body>
    <!-- header -->
      <%= render "layouts/header" %>

    <!-- Body部分 -->
    <div class="container min-vh-100">
      <%= yield %>
    </div>

    <!-- footer -->
    <%= render "layouts/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
    
    <span id="back">
      <a href="#">
        <img src="<%= asset_path('arrow.png') %>" alt="">
      </a>
    </span>
    <!-- モーダル -->
    <div id="modal" class="modal">
        <span id="close">×</span>
        <img class="modal-content" id="modalImage">
    </div>

  <%= javascript_pack_tag 'arrow', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'hamburger_menu', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'modal', 'data-turbolinks-track': 'reload' %>
  </body>
</html>